title: Jaqueline Moreira
#logo:
description: "ğŸ‘©ğŸ»â€ğŸ’» Hi there! My name is Jaqueline Moreira. I have a bachelor's degree in Statistics and an MBA with a specialization in Data Science and Analytics. Iâ€™m a curious and focused number geek,ğŸ¤“ and Iâ€™m looking forward to facing new challenges and improving my skills."
theme: jekyll-theme-minimal
